# Generated by Django 3.2.21 on 2023-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
